include $(RIOTCPU)/efm32/efm32-info.mk

FEATURES_PROVIDED += periph_cpuid
FEATURES_PROVIDED += periph_flashpage
FEATURES_PROVIDED += periph_pm

if $(EFM32_TNRG_PRESENT)
    FEATURES_PROVIDED += periph_hwrng
endif
