# This file is automatically generated, and should not be changed. There is
# probably little reason to edit this file anyway, since it should already
# contain all information for the EFR32MG22 family of CPUs.

# Series - Architecture - Flash base - Flash size - SRAM base - SRAM size - Crypto? - TRNG? - Radio?
EFM32_INFO_efr32mg22c224f512im40 = 2 cortex-m33 0x00000000 0x00080000 0x20000000 0x00008000 1 1 1
EFM32_INFO_efr32mg22c224f512im32 = 2 cortex-m33 0x00000000 0x00080000 0x20000000 0x00008000 1 1 1
EFM32_INFO_efr32mg22c224f512gn32 = 2 cortex-m33 0x00000000 0x00080000 0x20000000 0x00008000 1 1 1
EFM32_INFO_efr32mg22a224f512im40 = 2 cortex-m33 0x00000000 0x00080000 0x20000000 0x00008000 1 1 1
