PKG_NAME=emlib
PKG_URL=https://github.com/basilfx/emlib
PKG_VERSION=cd36cd4f1a2a4566b19d9c7d30b8cc2913fe5292
PKG_LICENSE=Zlib

.PHONY: all

all: git-download
	"$(MAKE)" -C $(PKG_BUILDDIR)

include $(RIOTBASE)/pkg/pkg.mk
