# This file is automatically generated, and should not be changed. There is
# probably little reason to edit this file anyway, since it should already
# contain all information for the EFM32PG12B family of CPUs.

# Series - Architecture - Flash base - Flash size - SRAM base - SRAM size - Crypto? - TRNG? - Radio?
EFM32_INFO_efr32fg13p232f512gm48 = 1 cortex-m4f 0x00000000 0x00080000 0x20000000 0x00010000 1 1 1
EFM32_INFO_efr32fg13p231f512im48 = 1 cortex-m4f 0x00000000 0x00080000 0x20000000 0x00010000 1 1 1
EFM32_INFO_efr32fg13p231f512gm32 = 1 cortex-m4f 0x00000000 0x00080000 0x20000000 0x00010000 1 1 1
EFM32_INFO_efr32fg13p233f512gm48 = 1 cortex-m4f 0x00000000 0x00080000 0x20000000 0x00010000 1 1 1
EFM32_INFO_efr32fg13p231f512gm48 = 1 cortex-m4f 0x00000000 0x00080000 0x20000000 0x00010000 1 1 1
EFM32_INFO_efr32fg13p231f512im32 = 1 cortex-m4f 0x00000000 0x00080000 0x20000000 0x00010000 1 1 1
EFM32_INFO_efr32fg13p232f512gm32 = 1 cortex-m4f 0x00000000 0x00080000 0x20000000 0x00010000 1 1 1
