export CPU_ARCH = cortex-m3
export CPU_FAM = ezr32lg
export CPU_SERIES = 0

# include vendor device headers
export INCLUDES += -I$(RIOTCPU)/ezr32lg/include/vendor

# include cortexm_common
include $(RIOTMAKE)/arch/cortexm.inc.mk

# include efm32_common
include $(RIOTCPU)/efm32_common/Makefile.include
