{% strip 2 %}
    {% if crypto and development %}
        FEATURES_PROVIDED += periph_hwcrypto
    {% endif %}
{% endstrip %}
{% strip 2 %}
    {% if trng %}
        FEATURES_PROVIDED += periph_hwrng
    {% endif %}
{% endstrip %}

include $(RIOTCPU)/efm32_common/Makefile.features
