export CPU_ARCH = cortex-m3
export CPU_FAM = efm32gg
export CPU_SERIES = 0

# include vendor device headers
export INCLUDES += -I$(RIOTCPU)/efm32gg/include/vendor

# include cortexm_common
include $(RIOTMAKE)/arch/cortexm.inc.mk

# include efm32_common
include $(RIOTCPU)/efm32_common/Makefile.include
