ifneq (,$(filter saul_default,$(USEMODULE)))
    USEMODULE += saul_gpio
    {% strip 2 %}
        {% if board in ["slstk3401a", "slwstk6220a"] %}
            USEMODULE += si70xx
        {% endif %}
        {% if board in ["sltb001a"] %}
            USEMODULE += bmp280
            {% strip 2 %}
                {% if development %}
                    USEMODULE += ccs811
                    USEMODULE += icm_20648
                    USEMODULE += si11x3
                {% endif %}
            {% endstrip %}
            USEMODULE += si70xx
            {% strip 2 %}
                {% if development %}
                    USEMODULE += si7210a
                {% endif %}
            {% endstrip %}
        {% endif %}
    {% endstrip %}
endif
