ifneq (,$(filter saul_default,$(USEMODULE)))
    USEMODULE += saul_gpio
    {% strip 2 %}
        {% if board in ["slstk3401a", "slstk3402a", "slwstk6220a"] %}
            USEMODULE += si7021
        {% endif %}
        {% if board in ["sltb001a"] %}
            USEMODULE += bmp280
            {% strip 2 %}
                {% if development %}
                    USEMODULE += ccs811
                    USEMODULE += icm_20648
                    USEMODULE += si11x3
                {% endif %}
            {% endstrip %}
            USEMODULE += si7021
            {% strip 2 %}
                {% if development %}
                    USEMODULE += si7210a
                {% endif %}
            {% endstrip %}
        {% endif %}
    {% endstrip %}
endif

{% strip 2, "<" %}
    {% if board in ["slstk3401a", "slstk3402a", "slwstk622a"] %}
        # i2c is required for Si7021
        USEMODULE += periph_i2c
    {% elif board in ["sltb001a"] %}
        # i2c is required for environmental sensors
        USEMODULE += periph_i2c
    {% endif %}
{% endstrip %}
