ifneq (,$(filter saul_default,$(USEMODULE)))
    USEMODULE += saul_gpio
    {% strip 2 %}
        {% if board in ["slstk3401a", "slwstk6220a", "sltb001a"] %}
            USEMODULE += si70xx
        {% endif %}
    {% endstrip %}
endif
