ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
  USEMODULE += bmp280_i2c
  USEMODULE += ccs811
  USEMODULE += icm_20648
  USEMODULE += si11x3
  USEMODULE += si7021
  USEMODULE += si7210
endif

# add board common drivers
USEMODULE += boards_common_silabs
USEMODULE += silabs_pic

# include board common dependencies
include $(RIOTBOARD)/common/silabs/Makefile.dep
