ifneq (,$(filter saul_default,$(USEMODULE)))
    USEMODULE += saul_gpio
    USEMODULE += bmp280
    USEMODULE += ccs811
    USEMODULE += icm_20648
    USEMODULE += si11x3
    USEMODULE += si7021
    USEMODULE += si7210a
endif

# include board common dependencies
include $(RIOTBOARD)/common/silabs/Makefile.dep

include $(RIOTCPU)/efm32/Makefile.dep
