export CPU_ARCH = cortex-m3
export CPU_FAM = efm32jg1b
export CPU_SERIES = 1

# include vendor device headers
export INCLUDES += -I$(RIOTCPU)/efm32jg1b/include/vendor

# include cortexm_common
include $(RIOTMAKE)/arch/cortexm.inc.mk

# include efm32_common
include $(RIOTCPU)/efm32_common/Makefile.include
